#!/bin/bash

declare -a REPO_LIST=($(curl -s https://api.github.com/users/mattialancellotti/repos \
  | jq '.[] | .name ' \
  | tr --delete \"))

log()  { echo "[@@] $1" >&1; }
warn() { echo "[!!] $1" >&2; }

log "Displaying all your repositories:"
for value in ${REPO_LIST[@]}; do
  echo -e "\t$value"
done
