#!/bin/bash
#
#==============================================================================
#
#         FILE: buks
#
#        USAGE: TODO
#
#  DESCRIPTION: TODO
#
#      OPTIONS: See usage function below.
# REQUIREMENTS: TODO
#         BUGS: ---
#        NOTES: TODO
#       AUTHOR: Lancellotti Mattia
#      COMPANY: ---
#      VERSION: 1.0
#      CREATED: 30/09/2021
#     REVISION: ---
#==============================================================================

# Sourcing necessary files
source $DOTFILES/../include/logging.sh
source $DOTFILES/../include/system.sh

# Books will be stored in this directory
BOOKS_DIR="${HOME}/books"

# Checking if nnn is installed
check_command nnn     || die_on_error "You need nnn to run the script" 1;
check_command zathura || die_on_error "You need zathura to run the script" 1;

# Checking if the directory exists
[ ! -d $BOOKS_DIR ] && \
  mkdir $BOOKS_DIR && warn "No books found." && exit 1;

# Listing books
IFS=$'\n'
BUKS=($(ls -w 1 $BOOKS_DIR))

[ ${#BUKS[@]} -eq 1 ] && zathura "$BOOKS_DIR/${BUKS[0]}" && exit 0;

# Opening the explorer
nnn $BOOKS_DIR;
exit 0;
