#!/bin/bash
#
#==============================================================================
#
#         FILE: chlog
#
#        USAGE: chlog [ <changes> | --new-version, -n <version number> ]
#
#  DESCRIPTION: This script checks if there is a CHANGELOG.md in the current
#               working directory and appends to it a new version or a new
#               change.
#
#      OPTIONS: See usage function below.
# REQUIREMENTS: bash
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Lancellotti Mattia
#      COMPANY: ---
#      VERSION: 1.0
#      CREATED: 13/09/2021
#     REVISION: ---
#==============================================================================

HEADER="CHANGELOG\n---------\n"

source $DOTFILES/../include/logging.sh

usage() {
  echo "chlog [ <changes> | --new-version, -n <version number> ]";
}

# If no argument is supplied echo the script's usage
[ $# -eq 0 ] && usage && exit 0;

# By default this script will check if there is a changelog in the current
# directory (CHANGELOG.md). If it doesn't exist then the first version must be
# specified.
if [[ "$1" == "--new-version" || "$1" == "-n" ]]; then
  [ ! -f "CHANGELOG.md" ] && echo -e $HEADER >> CHANGELOG.md;

  echo -e "* Version $2:" >> CHANGELOG.md;
else
  [ ! -f "CHANGELOG.md" ] &&
    warn "You must use --new-version before adding changes" && exit 1;

  echo -e "\t- $(date +%d%m%Y) $@" >> CHANGELOG.md;
fi

exit 0;
