#!/bin/bash
#
#==============================================================================
#
#         FILE: cottage
#
#        USAGE: TODO
#
#  DESCRIPTION: TODO
#
#      OPTIONS: See usage function below.
# REQUIREMENTS: TODO
#         BUGS: ---
#        NOTES: TODO
#       AUTHOR: Lancellotti Mattia
#      COMPANY: ---
#      VERSION: 1.0
#      CREATED: 27/12/2021
#     REVISION: ---
#==============================================================================

PKGS="/tmp/radioactive_wastes";

# Reads all the entries in world, then checks whether they are needed by some
# other programs. If not it is going to report it to the user.
while read -r pkg;
do
  # Using equery to check dependencies.
  if [ -z "$(equery --quiet depends $pkg)" ];
  then
    # Asking the user what to do next.
    read -p "[~] $pkg? " answer < /dev/stdout;
    if [[ "$answer" == "yes" ]];
    then
      echo "Deleting $pkg.";
      echo "$pkg" >> $PKGS;
    fi
  fi
done < "/var/lib/portage/world";

[ ! -s $PKGS ] && exit 0;

# Cleaning portage's tree
doas emerge --deselect $(cat $PKGS);
doas emerge --ask --depclean;

rm -f $PKGS;
