#!/bin/bash
#
#==============================================================================
#
#         FILE: fast-pass
#
#        USAGE: TODO
#
#  DESCRIPTION: TODO
#
#      OPTIONS: See usage function below.
# REQUIREMENTS: TODO
#         BUGS: ---
#        NOTES: TODO
#       AUTHOR: Lancellotti Mattia
#      COMPANY: ---
#      VERSION: 1.0
#      CREATED: 01/11/2021
#     REVISION: ---
#==============================================================================

# Activating extended pattern matching
shopt -s extglob

source $UTILITIES/include/system.sh
source $UTILITIES/include/logging.sh

# This script needs gpg
check_command gpg || die_on_error "You need gpg to encrypt your passwords." 1;

# Creating a local database
PROG_FILES=${HOME}/.local/share/fast-pass
LOCAL_DB="$PROG_FILES/passwords.tar"
ENCRYPTED_DB="$LOCAL_DB.gpg"

mkdir -p $PROG_FILES

usage() {
  log "fast-pass - simple bash script to store passwords."
  cat <<- EOF
  -h, --help : prints out this message.
  -l, --list : lists all the stored passwords.
  -n, --new  : stores a new password (via input).
  -d, --del  : deletes a stored password.
  --delete-all ! deletes all the passwords.

  Examples:
    fast-pass [-l|--list]       : (Will list all the saved passwords)
    fast-pass (-n|--new) <name> : (Will store the new password under <name>)
    fast-pass <name>            : (If it exists ? show the password : create it)
EOF
}

# Listing all the passwords
# TODO:
#   - Nice formatting of the passwords;
#   - Maybe add the date it was added (creation date of the file);
list_passwds() {
  [ ! -f $ENCRYPTED_DB ] && \
    log "No passwords saved." && exit 0;

  # Decrypting and listing the content of the archive
  gpg --decrypt --no-symkey-cache --output $LOCAL_DB $ENCRYPTED_DB;
  [ $? -ne 0 ] && die_on_error "Wrong password." 1;

  tar -tvf $LOCAL_DB | awk '{print $6" (D"$4"T"$5")"}';

  # Removing the decrypted archive by shreding it
  shred --remove=wipesync --zero --exact $LOCAL_DB;
}

chck_passwd() {
  [ ! -f $ENCRYPTED_DB ] && return 0;
    #create_passwd $1 && exit 0;

  # Decrypting the database to check whether the given password is already
  # stored.
  gpg --decrypt --no-symkey-cache --output $LOCAL_DB $ENCRYPTED_DB;
  [ $? -ne 0 ] && die_on_error "Wrong password." 1;

  # Searching for the password.
  local hash=$(echo $1 | sha256sum | awk '{print $1}')
  tar -tvf $LOCAL_DB | \
    awk -v hash="$hash" \
    '{
      if ($6 == hash) exit 1;
      else            exit 0;
      }';

  return $?;
}

update_archive() {
  # Checking if the encrypted database is available.
  [ ! -f $ENCRYPTED_DB ] && die_on_error "No db found." 1;

  # Updating and re-encrypting the archive.
  tar -C /tmp -uf $LOCAL_DB $(basename $1);
  gpg --symmetric --output $ENCRYPTED_DB $LOCAL_DB;
}

create_archive() {
  # Checking if the encrypted database is available.
  [ -f $ENCRYPTED_DB ] && die_on_error "Database found." 1;

  # Creating the new archive and encrypting it.
  log "Creating the passwords database.";
  tar -C /tmp -cvf $LOCAL_DB "$(basename $1)";
  gpg --symmetric --no-symkey-cache --output $ENCRYPTED_DB $LOCAL_DB;
}

create_passwd() {
  ( chck_passwd $1 ) || die_on_error "Password already stored." 2;

  # Asking the user to input the password
  log "Type the password you want so store:"
  read -s passwd;

  local pfile_db="/tmp/$(echo $1 | sha256sum | awk '{print $1}')"
  echo $passwd > $pfile_db

  [ ! -f $ENCRYPTED_DB ] && \
    create_archive $(basename $pfile_db) || \
    update_archive $(basename $pfile_db);

  shred --remove=wipesync --zero --exact $pfile_db $LOCAL_DB;
}

# If no arguments were supplied, than list all the saved passwords.
[ $# -eq 0 ] && list_passwds

# Parses the arguments passed to the script.
set -- "$@"
while [ $# -gt 0 ]; do
  case "$1" in
    -n) create_passwd $2; exit 0;;

    --new=*) create_passwd ${1#*=}; exit 0;;

    --list|-l) list_passwds; shift 1;;
    --help|-h) usage; exit 0;;

    --del|-d) log "Coming soon"; shift 1;;
    --get|-g) log "Coming soon"; shift 1;;
    --delete-all) rm -rf $ENCRYPTED_DB; exit 0;;

    @(-*)) warn "Unknown parameter $1."; exit 1;;
    *) chck_passwd $1; exit $?;;
  esac
done

exit 0;
