#!/bin/bash

source $DOTFILES/../include/logging.sh

HUBLINK=https://github.com/mattialancellotti
declare -a REPO_LIST=($(curl -s https://api.github.com/users/mattialancellotti/repos \
  | jq '.[] | .name ' \
  | tr --delete \"))

log "Displaying all your repositories from $HUBLINK"
for repository in ${REPO_LIST[@]}; do
  # Defining path of the local repository
  LOCAL_REPO="$HOME/code/$repository"

  [ -d $LOCAL_REPO ] && \
    echo "[✓] $repository synched in $LOCAL_REPO." || \
    echo "[✗] $repository not synched."
done
