#!/bin/sh

# Needed for `die_on_error`
. $UTILITIES/include/system.sh
. $UTILITIES/include/logging.sh

# Checking if the script was used the right way
[ $# -ne 1 ] && die_on_error "Usage: mkscript <script name>" 1;

# Creating the name and checking if the script doesn't exist already
SCRIPT_NAME=${UTILITIES}/scripts/${1}
check_command ${1} && die_on_error "${SCRIPT_NAME} already exists." 1;

DATE=$(date +"%d/%m/%Y")
echo "#!/bin/bash
#
#==============================================================================
#
#         FILE: ${1}
#
#        USAGE: TODO
#
#  DESCRIPTION: TODO
#
#      OPTIONS: See usage function below.
# REQUIREMENTS: TODO
#         BUGS: ---
#        NOTES: TODO
#       AUTHOR: Lancellotti Mattia
#      COMPANY: ---
#      VERSION: 1.0
#      CREATED: ${DATE}
#     REVISION: ---
#==============================================================================
" >> ${SCRIPT_NAME}

chmod +x $SCRIPT_NAME
$EDITOR $SCRIPT_NAME
