#!/bin/sh

. $UTILITIES/include/system.sh

check_command borg || die_on_error "You need borg to run this script." 1;

BORG_DEVICE="/dev/sda6"        # Backup device
KEYS_EXPORT="${HOME}/keys.gpg" # Backup gpg keys

# Checking that the device is mounted
MOUNT_POINT=$(findmnt ${BORG_DEVICE} -n -o TARGET)
[ -z $MOUNT_POINT ] && exit 1

# Exporting gpg keys
echo "Exporting your gpg keys."
gpg --export --output $KEYS_EXPORT

# Creating a new backup
echo "Creating your backup."
borg create --verbose --noatime \
  --stats --list --numeric-owner \
  --progress --comment "$1" \
  --compression auto,zstd,15 \
  "${MOUNT_POINT}/backups"::{user}-{now:%Y-%m-%dT%H:%M:%S} \
  /etc/ ${HOME}/music $KEYS_EXPORT ${HOME}/code ${HOME}/books \
  ${HOME}/uniud ${HOME}/documents ${HOME}/pictures /var/lib/portage \
  /proc/config.gz ${HOME}/.local/bin/dotfiles \
  --exclude-caches

# Deleting old backups
echo "Deleting old backups."
borg prune --verbose --list \
  --prefix="{user}-" --keep-within=10d --keep-weekly=4 --keep-monthly=1 \
  "${MOUNT_POINT}/backups"

echo "Deleting exported keys"
[ -f $KEYS_EXPORT ] && rm -v $KEYS_EXPORT
