#!/bin/sh

# -- FUNCTION --
#        NAME: check_command
# DESCRIPTION: Checks whether a program is available through a built-in.
# PARAMETER 1: Program needed.
check_command() { command -v "$1" 1> /dev/null; }

# -- FUNCTION --
#        NAME: err
# DESCRIPTION: Report errors to the users.
# PARAMETER 1: Message to report.
err() { [ $# -gt 0 ] && echo "!! $1" >&2; }

# Checking if the script was used the right way
if [ $# -ne 1 ]; then
  err "Usage: mkscript <script name>";
  exit 1;
fi

# Creating the name and checking if the script doesn't exist already
SCRIPT_NAME=${UTILITIES}/scripts/${1}
check_command ${1} && {
  err "${SCRIPT_NAME} already exists.";
  exit 1;
}

DATE=$(date +"%d/%m/%Y")
echo "#!/bin/bash
#
#==============================================================================
#
#         FILE: ${1}
#
#        USAGE: TODO
#
#  DESCRIPTION: TODO
#
#      OPTIONS: See usage function below.
# REQUIREMENTS: TODO
#         BUGS: ---
#        NOTES: TODO
#       AUTHOR: Lancellotti Mattia
#      COMPANY: ---
#      VERSION: 1.0
#      CREATED: ${DATE}
#     REVISION: ---
#==============================================================================
" >> ${SCRIPT_NAME}

chmod +x $SCRIPT_NAME
$EDITOR $SCRIPT_NAME
